// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE58x9QSE3fLqkNdqlKqZmTczvpFYUYoQ',
    appId: '1:525495132469:web:8ad706a760f9c931442c7c',
    messagingSenderId: '525495132469',
    projectId: 'blackjack-projektgrupp8',
    authDomain: 'blackjack-projektgrupp8.firebaseapp.com',
    storageBucket: 'blackjack-projektgrupp8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqgOX2PwIKdh9E-VOpHZRIbe7Ynt_vPdg',
    appId: '1:525495132469:android:8277267b1a11ed25442c7c',
    messagingSenderId: '525495132469',
    projectId: 'blackjack-projektgrupp8',
    storageBucket: 'blackjack-projektgrupp8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPs4W2Roir5Dvc6qknwilzNBqSS1knr-k',
    appId: '1:525495132469:ios:bcbe6a543620ef98442c7c',
    messagingSenderId: '525495132469',
    projectId: 'blackjack-projektgrupp8',
    storageBucket: 'blackjack-projektgrupp8.appspot.com',
    iosClientId: '525495132469-0f7pc76es0l4pqlh8f2gtv9631pepm3u.apps.googleusercontent.com',
    iosBundleId: 'se.gu.myFirstApp',
  );
}
